Fix of unknown Ringbuffer and not found USB-Serial Device
micro-ROS/micro_ros_zephyr_module pull request #125
Opened 2023-10-22 13:01 UTC by scrapforge

I added in prj.conf a CONFIG_RING_BUFFER=y line, due to an error while building, which stated an undefined reference occured, similar to this on https://github.com/zephyrproject-rtos/zephyr/issues/30183. 
Also i could not reliably reproduce the error. This line fixed any appearance of it.

Also if usb-serial configured as transport layer for microros, the code hang up. After a lot of debugging i found that in the file mymicromodule/modules/libmicroros/microros_transports/serial-usb/microros_transports.c the device is searched by its label CDC_ACM_0. Therefore an app.overlay file is needed, which i added.

I have used 
zephyr 3.5.0-rc3
and
zephyr-sdk 0.16.3

2023-10-24 06:59 UTC, pablogs9 commented
> I added in prj.conf a CONFIG_RING_BUFFER=y line, due to an error while building, which stated an undefined reference occured, similar to this on https://github.com/zephyrproject-rtos/zephyr/issues/30183.

Could you provide details on how to trigger this build error?


Also, the CI seems to have errors

2023-10-24 08:08 UTC, scrapforge commented
The CI for Zephyr 2.7.2 complains about:
Error: disco_l475_iot1.dts.pre.tmp:1921.1-13 Label or path zephyr_udc0 not found
FATAL ERROR: Syntax error parsing input tree.

I considered the error could be based on an api/syntax change between the versions 2.7.2 and 3.1 but as i searched the documentation for Zephyr 2.7.2 i found, that the added overlay code is the same as proposed in
https://docs.zephyrproject.org/2.7.2/reference/usb/uds_cdc_acm.html?highlight=zephyr_udc0.

So i compared the device-tree overlays disco_l475_iot1.dts for the board and got (just the important detail):
-&usbotg_fs {
+zephyr_udc0: &usbotg_fs {
        pinctrl-0 = <&usb_otg_fs_dm_pa11 &usb_otg_fs_dp_pa12
                     &usb_otg_fs_id_pa10>;
+       pinctrl-names = "default";
        status = "okay";
 };
 
So error is caused by a change in the devicetree-overlay.
Do you have a idea how to solve this?

2023-10-24 08:14 UTC, scrapforge commented
-  &usbotg_fs {
     +  zephyr_udc0: &usbotg_fs {
          pinctrl-0 = <&usb_otg_fs_dm_pa11 &usb_otg_fs_dp_pa12
                       &usb_otg_fs_id_pa10>;
     +         pinctrl-names = "default";
          status = "okay";
        };

Im sorry for the mess. The github text parser surprised me.

2023-10-24 08:17 UTC, pablogs9 commented
Can you update the PR?

2023-10-24 08:21 UTC, scrapforge commented
I'm sorry, but i dont understand you. Could you explain it?

2023-10-24 08:33 UTC, pablogs9 commented
Sure, I wonder if you can update the PR with the required changes in order to make the CI pass.

2023-10-24 09:18 UTC, scrapforge commented
> > I added in prj.conf a CONFIG_RING_BUFFER=y line, due to an error while building, which stated an undefined reference occured, similar to this on [zephyrproject-rtos/zephyr#30183](https://github.com/zephyrproject-rtos/zephyr/issues/30183).
> 
> Could you provide details on how to trigger this build error?

Steps to trigger this error:
- follow instructions of the latest zephyr release and install zephyr and zephyr sdk
- mkdir .../zephyrproject/applications
- cd .../zephyrproject/applications
- clone https://github.com/micro-ROS/micro_ros_zephyr_module
- west build -p always -b nucleo_h743zi micro_ros_zephyr_module

results in the error message:

    .../zephyrproject/applications/micro_ros_zephyr_module/modules/libmicroros/microros_transports/serial/microros_transports.c:44: undefined reference to `ring_buf_put'
    .../zephyrproject/applications/micro_ros_zephyr_module/modules/libmicroros/microros_transports/serial/microros_transports.c:102: undefined reference to `ring_buf_get'

2023-10-24 09:28 UTC, pablogs9 requested changes

2023-10-24 09:28 UTC, pablogs9 commented on prj.conf
> +
```suggestion
```

2023-10-24 09:29 UTC, pablogs9 requested changes

2023-10-24 09:29 UTC, pablogs9 commented on app.overlay
> +*/
```suggestion
/* Added these lines for compatibility with Zephyr v2.7 */
```

2023-10-24 09:33 UTC, scrapforge commented on app.overlay
> +*/
I changed it but i messed it up in github so it is still marked as a change request

2023-10-24 13:20 UTC, pablogs9 commented on app.overlay
> +};
Is it possible to retrieve the device without labeling it? Maybe it is a better idea to change the line 

```c
 params->uart_dev = device_get_binding("CDC_ACM_0");
```

in the transport. Is this possible?

2023-10-24 13:20 UTC, pablogs9 commented on app.overlay
> +};
Does the error related to this appear when building with USB-CDC enabled? I have found that we are only building Serial transport on CI.

2023-10-24 13:24 UTC, pablogs9 commented on prj.conf
> +CONFIG_RING_BUFFER=y
Is it possible to embedded this dependency of the USB CDC transport at KConfig level. Something like the following in `modules/libmicroros/KConfig`

```
    choice
        prompt "micro-ROS transport"

        config MICROROS_TRANSPORT_SERIAL
            bool "micro-ROS serial transport"

        config MICROROS_TRANSPORT_SERIAL_USB
            bool "micro-ROS USB serial transport"

        config MICROROS_TRANSPORT_UDP
            bool "micro-ROS UDP network transport"

    endchoice

    if MICROROS_TRANSPORT_SERIAL_USB
        SELECT RING_BUFFER
    endif
```

2023-10-24 13:36 UTC, pablogs9 commented on app.overlay
> +};
I'm gonna enable the Serial and Serial USB build at CI here: https://github.com/micro-ROS/micro_ros_zephyr_module/pull/126

2023-10-24 13:47 UTC, pablogs9 commented
https://github.com/micro-ROS/micro_ros_zephyr_module/pull/126 merged, could you rebase?

2023-10-24 20:04 UTC, scrapforge commented
> #126 merged, could you rebase?

I hope i did it right.

2023-10-24 20:28 UTC, scrapforge commented on app.overlay
> +};
This specific error fixed by this snippet appears in in the CI with zephyr v2.7 because it was added later into the standard devicetree overlay. So as my other code refers to Zephyr 3.1 and 3.5., where this is implemented in the standard devicetree-file of the boards, i considered it the smoothest solution. 
Since the 2.7 is still developed, you could argue, that it should be merged in there. But i dont know which boards support this device. So to avoid mysteriously working and not working boards its better here.

2023-10-24 20:36 UTC, scrapforge commented on app.overlay
> +};
The problem that I ran into was that my code did compile, but when i flashed it, it didn't work. It took me while to understand, that the problem was caused by this line
> ```c
> device_get_binding("CDC_ACM_0");
> ```

which tried to get the device, by a label/name not known. So the surrounding RCCHECK of the function, which calls this code line, did throw an error:
> ```c
>RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));
> ```

So i dont think that any CI, would actually detect my problem, because it only shows up at runtime.

2023-10-24 20:39 UTC, scrapforge commented
The problem that I ran into was that my code did compile, but when i flashed it, it didn't work. It took me while to understand, that the problem was caused by this line
> ```c
> device_get_binding("CDC_ACM_0");
> ```

which tried to get the device, by a label/name not known. So the surrounding RCCHECK of the function, which calls this code line, did throw an error:
> ```c
>RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));
> ```

So i dont think that any CI, which only compiles the code (as far as i unterstand the log), would actually detect my problem, because it only shows up at runtime. 

So i only can confirm my solution for my setup
(Zephyr 3.5, Zephyr-Sdk 0.16, Board stm32h743zi)

2023-10-25 13:46 UTC, scrapforge commented
I> Is it possible to embedded this dependency of the USB CDC transport at KConfig level. Something like the following in `modules/libmicroros/KConfig`
> 
It is possible, also all warnings to the use of "select" in Kconfig  apply. 
The only other option i found, would to use set(<TRANSPORT_VARIABLE> 1 ) in CMake and use this to conditional add .conf files. But this couldn't be managed by Kconfig anymore, because this has to be done before Zephyr is included.

2023-10-26 05:27 UTC, pablogs9 requested changes
Last changes and we can merge

2023-10-26 05:27 UTC, pablogs9 commented on prj.conf
> +
```suggestion
```

2023-10-26 05:27 UTC, pablogs9 commented on modules/libmicroros/Kconfig
> +
```suggestion

```

2023-10-26 12:48 UTC, pablogs9 commented
@mergify backport humble rolling

2023-10-26 12:48 UTC, merged