boards: move board specific configurations
micro-ROS/micro_ros_zephyr_module pull request #63
Opened 2022-07-26 22:25 UTC by uLipe

Te idea is to keep consistent with other zephyr modules and separate board specific details into their own overlays.

Also add the example l475 IoT discovery board as an example.

No changes in the environment or build.

2022-07-26 22:25 UTC, uLipe commented
@pablogs9 @Acuadros95 PTAL.

2022-07-27 06:13 UTC, pablogs9 commented
Running CI, thanks a lot @uLipe

2022-07-27 06:13 UTC, pablogs9 commented
@mergify backport foxy galactic main

2022-07-27 06:30 UTC, pablogs9 commented
It seems to break the CI @uLipe : https://github.com/micro-ROS/micro_ros_zephyr_module/runs/7534484810?check_suite_focus=true#step:4:5888

2022-07-27 15:19 UTC, uLipe commented
@pablogs9 my bad, during rebase I dropped a piece of the dts I will change this to draft while I fix it

2022-07-27 15:29 UTC, pablogs9 commented
Thanks. Maybe we should investigate the working status of this module in 2.7 @Acuadros95

2022-07-27 16:15 UTC, uLipe commented
@pablogs9 PTAL again, for now let's keep compatible with 2.6.

Actually I have this running on Zephyr 3.1 but using the overlay + kconfig updates that broke the CI + this PR https://github.com/ros2/rcutils/pull/368

2022-07-28 05:55 UTC, pablogs9 commented
Could you take a look at this https://github.com/micro-ROS/micro_ros_zephyr_module/pull/64 @uLipe. We would like to have this working with v3.1.0 as you have.

2022-07-28 15:31 UTC, uLipe commented
@pablogs9 , @Acuadros95 , I just took the opportunity to modify the zephyr transport serial port to use the DT macros, label property in the devices are being removed from Zephyr and will not work in future kernel releases.

Please take another review and ask me any questions you might to have.

2022-07-29 06:06 UTC, pablogs9 commented
I'll take a look on Monday when I have some hardware in the office

2022-08-02 06:08 UTC, pablogs9 requested changes

2022-08-02 06:08 UTC, pablogs9 commented on modules/libmicroros/microros_transports/serial-usb/microros_transports.c
>      if (!params->uart_dev) {
`params` undefined here

2022-08-02 06:08 UTC, pablogs9 commented on modules/libmicroros/microros_transports/serial-usb/microros_transports.c
> +        uart_line_ctrl_get(uart_dev, UART_LINE_CTRL_DTR, &dtr);
Where is `uart_dev` defined?

2022-08-02 06:36 UTC, pablogs9 commented
Hello @uLipe:
- I have been able to test this with serial transport in `disco_l475_iot1`
- **Not** able to build the serial-usb example
- Should we drop the support for v2.4.0 if we merge this PR?

2022-08-04 17:56 UTC, uLipe commented
Hi @pablogs9 any updates regarding your tests?

About the Zephyr version I think it is safe to drop the 2.4 support, since most of V2 users would go to version 2.6 or 2.7, the last one is a LTS version.

There is no Zephyr-API breaking changes across 2.4 to 2.7, the same is not true for the build system for example, depending on what changed in a particular subsystem.

2022-08-05 06:20 UTC, pablogs9 commented
Hello @uLipe, I'll check this on Monday in the office, because I have no boards right now.

Meanwhile, I would like to drop 2.4 and add 2.7 in this PR: https://github.com/micro-ROS/micro_ros_zephyr_module/pull/64 is it possible for you to take a look there?

2022-08-08 06:11 UTC, pablogs9 commented
Hello @uLipe, I have been able to build the USB example but I have the following error:

```
*** Booting Zephyr OS build v2.6.0-rc1  ***
Failed to enable USB
```

Any idea? I'm working in the disco_l475_iot1

2022-08-08 11:39 UTC, uLipe commented
What is the ERRNO @pablogs9 ?  Have you tried in a different board like that?

2022-08-08 12:37 UTC, pablogs9 commented
That's our reference board for Zephyr, not sure if I have other. `errno` is 0 (?!?!)

```c
    ret = usb_enable(NULL);
    if (ret != 0) {
        printk("Failed to enable USB %d\n",errno);
        return false;
    }
```

result in 

```
*** Booting Zephyr OS build v2.6.0-rc1  ***
Failed to enable USB 0
```

2022-08-08 13:10 UTC, uLipe commented
actually ret comes with the error code translated into errno code, could you print ret instead?

My board currently opens and attches to the usb correctly.

2022-08-09 05:23 UTC, pablogs9 commented
```c
    ret = usb_enable(NULL);
    if (ret != 0) {
        printk("Failed to enable USB %d\n", ret);
        return false;
    }
```

results in 

```
*** Booting Zephyr OS build v2.6.0-rc1  ***
Failed to enable USB -5
```

Any idea?

2022-08-09 07:14 UTC, pablogs9 commented
I have been testing `samples/subsys/usb/cdc_acm` with my board and I have:

```
*** Booting Zephyr OS build zephyr-v3.1.0  ***
[00:00:00.034,000] <err> usb_dc_stm32: PCD_Init failed, 1
[00:00:00.034,000] <err> cdc_acm_echo: Failed to enable USB
```

This does not seems like a micro-ROS transport problem.

2022-08-09 10:10 UTC, pablogs9 commented
@uLipe I have updated the support here: https://github.com/micro-ROS/micro_ros_zephyr_module/pull/64

Please rebase this PR and we can merge since my USB-CDC problems are not related

BTW I have backported https://github.com/ros2/rcutils/pull/368 to `foxy`, `humble` and `galactic` in the micro-ROS fork.

2022-08-10 15:49 UTC, uLipe commented
@pablogs9 btw the error you re receiving is a timeout that is coming from USB endopoint, code 5 is -EIO, which is generated by the CDC ACM class when starting endpoint sending and no notification about the write is read back, are the connections, cable ot host computer okay? Do you see the enumeration on your host?

2022-08-10 18:47 UTC, uLipe commented
@pablogs9 rebase, please check one more time.

2022-08-11 06:00 UTC, pablogs9 requested changes

2022-08-11 11:12 UTC, uLipe commented on CHANGELOG.rst
>  * Update banner (`#56 <https://github.com/micro-ROS/micro_ros_zephyr_module/issues/56>`_)
Probably messed up the things during the rebase, will change that

2022-08-11 11:15 UTC, uLipe commented
@pablogs9 fixed the changelog, please do a check again.

2022-08-11 12:27 UTC, pablogs9 commented on CHANGELOG.rst
> +4.0.0 (2022-05-25)
```suggestion
3.0.0 (2022-05-25)
```

2022-08-11 12:28 UTC, pablogs9 approved these changes
LGTM, @Acuadros95 merge if you are ok

2022-08-17 10:07 UTC, Acuadros95 commented
@uLipe Could you take a look at the CI? [detail](https://github.com/micro-ROS/micro_ros_zephyr_module/runs/7786824074?check_suite_focus=true#step:4:6478)

```bash
/__w/micro_ros_zephyr_module/micro_ros_zephyr_module/micro_ros_zephyr_module/boards/disco_l475_iot1.conf:1: warning: attempt to assign the value 'y' to the undefined symbol USB
...

error: Aborting due to Kconfig warnings
```

2022-08-25 22:00 UTC, uLipe commented
@pablogs9 sorry for the delay, since we dropped the version 2.6 the CONFIG_USB symbol was also deprecated, I will remove it and update the PR

2022-08-25 22:22 UTC, uLipe commented
@pablogs9 @Acuadros95 I added the Zephyr UDC0 nodelabel, which replaces the CONFIG_USB from version 2.7 and above, please approve the workflow when you have time.

2022-08-26 06:11 UTC, pablogs9 approved these changes

2022-08-26 06:11 UTC, pablogs9 commented on CHANGELOG.rst
> +4.0.0 (2022-05-25)
```suggestion
3.0.0 (2022-05-25)
```

2022-08-26 06:12 UTC, pablogs9 commented on CHANGELOG.rst
> +4.0.0 (2022-05-25)
```suggestion
3.0.0 (2022-05-25)
```

2022-08-26 06:12 UTC, pablogs9 commented
@Acuadros95 PTAL and merger if you are ok

2022-08-26 06:57 UTC, Acuadros95 approved these changes
LGTM

2022-08-26 06:58 UTC, merged