Fix Zephyr include paths
micro-ROS/micro_ros_zephyr_module pull request #74
Opened 2022-08-22 08:13 UTC by pablogs9

Signed-off-by: Pablo Garrido <pablogs9@gmail.com>

2022-08-22 08:18 UTC, pablogs9 commented
@mergify backport master foxy galactic

2022-08-22 08:23 UTC, Acuadros95 approved these changes
LGTM

Does the new include path work if `CONFIG_LEGACY_INCLUDE_PATH` is on?

2022-08-22 08:26 UTC, pablogs9 commented
> Does the new include path work if `CONFIG_LEGACY_INCLUDE_PATH` is on?

It is ON by default. In any case, it works in both cases.

2022-08-22 08:30 UTC, pablogs9 commented
**Do not merge until decisions on Zephyr version support are taken**

2022-09-08 23:31 UTC, uLipe commented
@pablogs9 sorry for taking to long to review this.

The namespace of zephyr headers are a thing for releases of versions 3.x and above, and should not affect previous releases that adopt the namespacing on the headers.

2022-09-08 23:33 UTC, uLipe requested changes
please check the comments regarding zephyr.h

2022-09-08 23:33 UTC, uLipe commented on modules/libmicroros/microros_transports/serial/microros_transports.c
> +#include <zephyr/zephyr.h>
zephyr.h is deprecated on version 3.x please use kernel.h instead

2022-09-08 23:33 UTC, uLipe commented on src/main.c
> +#include <zephyr/zephyr.h>
zephyr.h is deprecated on version 3.x please use kernel.h instead

2022-09-08 23:33 UTC, uLipe commented
Just to update you, this also broke the rclc component, I will PR the fix.

2022-09-08 23:42 UTC, uLipe commented
Here is it:

https://github.com/ros2/rcutils/pull/383

2022-09-14 20:39 UTC, uLipe commented
@pablogs9 @Acuadros95 any updates on this?

2022-09-15 08:00 UTC, pablogs9 commented on modules/libmicroros/microros_transports/serial/microros_transports.c
> +#include <zephyr/zephyr.h>
Please apply this change

2022-09-15 08:00 UTC, pablogs9 commented on src/main.c
> +#include <zephyr/zephyr.h>
Same as above

2022-09-29 19:13 UTC, uLipe commented
@pablogs9 unfortunately I don't have permission to apply here,  I'll dupplicate the PR

2022-10-03 05:32 UTC, pablogs9 commented
Closing in favor of https://github.com/micro-ROS/micro_ros_zephyr_module/pull/82

2022-10-03 05:32 UTC, closed without merging